"""alter email column in Author table

Revision ID: 56dc179dd75b
Revises: 77f35dd4be27
Create Date: 2026-08-25 15:45:10.813138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # ADDED BY ME


# revision identifiers, used by Alembic.
revision: str = '56dc179dd75b'
down_revision: Union[str, Sequence[str], None] = '77f35dd4be27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
