"""adding embeddings column to Item table

Revision ID: 77f35dd4be27
Revises: e5e88bb3d1e2
Create Date: 2026-08-25 14:48:54.522602

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel  # ADDED BY ME

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77f35dd4be27"
down_revision: Union[str, Sequence[str], None] = "e5e88bb3d1e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item", "embedding")
    # ### end Alembic commands ###
